<a href="https://colab.research.google.com/github/EthanJF-Physics/MAT422/blob/main/MAT422HW1Ethan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Homework 1.2
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Basic Setup
matrix_size = 3 # For simplicty
def random_matrix(size: int=3):
    return np.random.randint(0,10, [size, size])
def proj(u,v):
    u = np.array(u, dtype=float)
    v = np.array(v, dtype=float)
    return np.multiply( (np.dot(v,u)/np.dot(u,u)) , u )
# Let's generate some matrcies for the rest of the code
A = random_matrix(matrix_size)
B = random_matrix(matrix_size)
print("Random 3by3 matrix A:\n", A)
print("\nRandom 3by3 matrix B:\n", B)

Random 3by3 matrix A:
 [[4 6 0]
 [2 3 9]
 [9 0 6]]

Random 3by3 matrix B:
 [[2 2 8]
 [0 8 0]
 [9 2 9]]


In [3]:
# 1.2.1 Linear Spaces
# Define some vetcors u1 and u2, lets use the columns of A
u1 = A[:, 0].astype(float)
u2 = A[:, 1].astype(float)
alpha = 2.5
# Vector Addition Closure Property
vector_sum = u1 + u2
print("Vector u1 (Col 1 of A):", u1)
print("Vector u2 (Col 2 of A):", u2)
print("Linear combination (u1 + u2):", vector_sum)
# Scalar Multiplication Closure Property
scalar_mult = alpha * u1
print(f"Scalar multiplication ({alpha} * u1):", scalar_mult)
# Linear Independence
test_matrix = np.column_stack((u1,u2))
matrix_rank = np.linalg.matrix_rank(test_matrix)
num_vectors = test_matrix.shape[1]
if matrix_rank == num_vectors:
    print("Result: u1 and u2 are LINEARLY INDEPENDENT.")
else:
    print("Result: u1 and u2 are LINEARLY DEPENDENT.")
# Find dim of U subspace
dim_U = np.linalg.matrix_rank(test_matrix)
print(f"Dimension of subspace U: {dim_U}")

Vector u1 (Col 1 of A): [4. 2. 9.]
Vector u2 (Col 2 of A): [6. 3. 0.]
Linear combination (u1 + u2): [10.  5.  9.]
Scalar multiplication (2.5 * u1): [10.   5.  22.5]
Result: u1 and u2 are LINEARLY INDEPENDENT.
Dimension of subspace U: 2


In [4]:
# 1.2.2 Orthogonality
# Orthonormal Bases
def inner_product(u, v):
    return np.dot(u, v)
def norm(b):
    return np.sqrt(inner_product(b, b))
# Show if orthogoal/orthonormal vectors
def check_ortho(u, v):
    is_gonal = np.isclose(inner_product(u, v), 0.0)
    is_normal = is_gonal and np.isclose(norm(u), 1.0) and np.isclose(norm(v), 1.0)
    return print("Orthgonal?", is_gonal, "Orthonormal?", is_normal)
# Show Cauchy-Swartz THM
def cauchy_schwarz(u, v):
    lhs = abs(inner_product(u, v))
    rhs = norm(u) * norm(v)
    result = lhs <= rhs or np.isclose(lhs, rhs)
    print("Cauchy-Schwarz Satisfied?", result)
    return result
# Show Orthogonal Proj and Decomp
def o_decomp(u, v):
    proj_v_on_u = (inner_product(v, u)) / inner_product(u, u) * u
    prep_v_on_u = v - proj_v_on_u
    print("Orthogonal Decompostion's Projection of v on u", proj_v_on_u)
    # verify using best approx thm
    is_orthogonal_residual = np.isclose(inner_product(prep_v_on_u, u), 0.0)
    print(f"  Best Approximation Check (perp ⊥ u): {is_orthogonal_residual}")
    return proj_v_on_u, prep_v_on_u

# Now Example with u1 and u2
print("\nOrthogonality & Orthonormality Check")
check_ortho(u1, u2)
print("\nCauchy-Schwarz Theorem Verification")
cauchy_schwarz(u1, u2)
print("\nOrthogonal Decomposition & Best Approximation")
proj_vector, perp_vector = o_decomp(u1, u2)
print("Orthogonal Decomposition's Perpendicular component:", perp_vector)



Orthogonality & Orthonormality Check
Orthgonal? False Orthonormal? False

Cauchy-Schwarz Theorem Verification
Cauchy-Schwarz Satisfied? True

Orthogonal Decomposition & Best Approximation
Orthogonal Decompostion's Projection of v on u [1.18811881 0.59405941 2.67326733]
  Best Approximation Check (perp ⊥ u): True
Orthogonal Decomposition's Perpendicular component: [ 4.81188119  2.40594059 -2.67326733]


In [5]:
# 1.2.3 Gran-Schmidt Process
def gram_schmidt_matrix(Matrix_Input):
    M = Matrix_Input.astype('float64')
    rows, cols = M.shape
    # U holds the orthogonal vectors, E holds the normalized orthonormal vectors
    U = np.zeros((rows, cols))
    E = np.zeros((rows, cols))
    # Process first column
    U[:, 0] = M[:, 0]
    E[:, 0] = U[:, 0] / np.linalg.norm(U[:, 0])
    # Process remaining columns
    for k in range(1, cols):
        u_k = M[:, k].copy()
        # Subtract projections onto all previously established orthogonal vectors
        for j in range(k):
            u_k -= proj(U[:, j], M[:, k])
        U[:, k] = u_k
        E[:, k] = U[:, k] / np.linalg.norm(U[:, k])
    return E
# Calculate the Gram-Schmidt Matrix of A
gs_A = gram_schmidt_matrix(A)
print("Gram-Schmidt Orthonormal Matrix of A:\n", gs_A)
# Verify identity (Q^T * Q = I)
identity_check = np.dot(gs_A.T, gs_A)
print("\nVerification (Identity Matrix Check gs_A^T * gs_A):\n", np.round(identity_check, 6))

Gram-Schmidt Orthonormal Matrix of A:
 [[ 3.98014876e-01  8.00989487e-01 -4.47213595e-01]
 [ 1.99007438e-01  4.00494744e-01  8.94427191e-01]
 [ 8.95533471e-01 -4.44994159e-01  8.96470666e-17]]

Verification (Identity Matrix Check gs_A^T * gs_A):
 [[ 1. -0.  0.]
 [-0.  1. -0.]
 [ 0. -0.  1.]]


In [6]:
# 1.2.4 Eigenvalues and Eigenvectors
# Calculate Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A.astype(float))
print("Eigenvalues of Matrix A:\n", eigenvalues)
print("\nEigenvectors of Matrix A (as columns):\n", eigenvectors)

# Verification of A * v = lambda * v for the first eigenvalue/eigenvector pair
lambda_1 = eigenvalues[0]
v_1 = eigenvectors[:, 0]
left_side = np.dot(A, v_1)
right_side = lambda_1 * v_1
print("\nVerification of A * v = lambda * v for first pair:")
print("A * v_1:\n", left_side)
print("lambda_1 * v_1:\n", right_side)
print(f"Are both sides equal? {np.allclose(left_side, right_side)}")

Eigenvalues of Matrix A:
 [12.70504095+0.j          0.14747953+6.18310464j  0.14747953-6.18310464j]

Eigenvectors of Matrix A (as columns):
 [[ 0.45144837+0.j          0.27903355+0.44783503j  0.27903355-0.44783503j]
 [ 0.65497942+0.j         -0.64066555+0.j         -0.64066555-0.j        ]
 [ 0.60596726+0.j          0.14104939-0.53966358j  0.14104939+0.53966358j]]

Verification of A * v = lambda * v for first pair:
A * v_1:
 [5.73567001+0.j 8.32154039+0.j 7.69883891+0.j]
lambda_1 * v_1:
 [5.73567001+0.j 8.32154039+0.j 7.69883891+0.j]
Are both sides equal? True
