<a href="https://colab.research.google.com/github/EthanJF-Physics/MAT422/blob/main/MAT422HW1Ethan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Many of the definitions, theorems, and lemmas are drawn from the first edition of Mathematical Methods in Data Science (January 6, 2023), published by Elsevier and authored by Jingli Ren and Haiyan Wang.

In [1]:
# Homework 1.2
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Basic Setup
matrix_size = 3 # For simplicty
def random_matrix(size: int=3):
    return np.random.randint(0,10, [size, size])
def proj(u,v):
    u = np.array(u, dtype=float)
    v = np.array(v, dtype=float)
    return np.multiply( (np.dot(v,u)/np.dot(u,u)) , u )
# Let's generate some matrcies for the rest of the code
A = random_matrix(matrix_size)
B = random_matrix(matrix_size)
print("Random 3by3 matrix A:\n", A)
print("\nRandom 3by3 matrix B:\n", B)

Random 3by3 matrix A:
 [[5 9 0]
 [5 6 2]
 [5 7 9]]

Random 3by3 matrix B:
 [[2 9 7]
 [9 9 8]
 [2 8 9]]


# Linear Spaces

## Linear Combinations

**Definition 1** *(Linear subspace)*. Let $U \subseteq V$ be a subset. $U$ is a linear subspace if it is closed under vector addition and scalar multiplication. That is, for all $u_1, u_2 \in U$ and $\alpha \in \mathbb{R}$, it holds that
$$u_1 + u_2 \in U \quad \text{and} \quad \alpha u_1 \in U$$
In particular, $0$ is always in a linear subspace. As we can see below, the span of a set of vectors is a linear subspace.

## Linear Independence

**Definition 2** *(Linear independence)*. A list of vectors $u_1, \dots, u_m$ is linearly independent if none of them can be written as a linear combination of the others—that is,
$$\forall i, \quad u_i \notin \operatorname{span}(\{u_j \mid j \neq i\})$$
A list of vectors is called linearly dependent if it is not linearly independent.

**Lemma 1** *(Characterization of linear independence)*. The vectors $u_1, \dots, u_m$ are linearly independent if and only if
$$\sum_{j=1}^{m} \alpha_j u_j = 0 \implies \alpha_j = 0 \quad \forall j$$
Equivalently, $u_1, \dots, u_m$ are linearly dependent if and only if there exist $\alpha_j$'s, not all zero, such that
$$\sum_{j=1}^{m} \alpha_j u_j = 0$$

**Theorem 1** *(Dimension theorem)*. Let $U$ be a linear subspace of $V$. Any basis of $U$ always has the same number of elements. All bases of $U$ have the same length, that is, the same number of elements. We call this number the dimension of $U$ and denote it $\dim(U)$.

**Lemma 2** *(Characterization of linearly dependent sets)*. Let $u_1, \dots, u_m$ be a linearly dependent list of vectors with a linearly independent subset $u_1, \dots, u_k$, where $k < m$. Then there is an $i > k$ such that:
1. $u_i \in \operatorname{span}(u_1, \dots, u_{i-1})$;
2. $\operatorname{span}(\{u_j \mid j \in \{1, \dots, m\}\}) = \operatorname{span}(\{u_j \mid j \in \{1, \dots, m\}, j \neq i\})$


In [4]:
# Define some vetcors u1 and u2, lets use the columns of A
u1 = A[:, 0].astype(float)
u2 = A[:, 1].astype(float)
alpha = 2.5
# Vector Addition Closure Property
vector_sum = u1 + u2
print("Vector u1 (Col 1 of A):", u1)
print("Vector u2 (Col 2 of A):", u2)
print("Linear combination (u1 + u2):", vector_sum)
# Scalar Multiplication Closure Property
scalar_mult = alpha * u1
print(f"Scalar multiplication ({alpha} * u1):", scalar_mult)
# Linear Independence
test_matrix = np.column_stack((u1,u2))
matrix_rank = np.linalg.matrix_rank(test_matrix)
num_vectors = test_matrix.shape[1]
if matrix_rank == num_vectors:
    print("Result: u1 and u2 are LINEARLY INDEPENDENT.")
else:
    print("Result: u1 and u2 are LINEARLY DEPENDENT.")
# Find dim of U subspace
dim_U = np.linalg.matrix_rank(test_matrix)
print(f"Dimension of subspace U: {dim_U}")

Vector u1 (Col 1 of A): [5. 5. 5.]
Vector u2 (Col 2 of A): [9. 6. 7.]
Linear combination (u1 + u2): [14. 11. 12.]
Scalar multiplication (2.5 * u1): [12.5 12.5 12.5]
Result: u1 and u2 are LINEARLY INDEPENDENT.
Dimension of subspace U: 2


## Orthonormal Bases

**Definition 3** *(Norm and inner product)*. For any vectors $u, v \in V$, the standard inner product and norm are defined as
$$\langle u, v \rangle = u \cdot v = \sum_{i=1}^{n} u_i v_i \quad \text{and} \quad \|u\| = \sqrt{\sum_{i=1}^{n} u_i^2}$$

**Definition 4** *(Orthonormal list)*. A list of vectors $u_1, \dots, u_m$ is orthonormal if the $u_i$'s are pairwise orthogonal and each has norm 1, that is, for all $i$ and all $j \neq i$,
$$\langle u_i, u_j \rangle = 0 \quad \text{and} \quad \|u_i\| = 1$$

**Lemma 3** *(Cauchy–Schwarz)*. For any $u, v \in V$, the inner product is bounded by the product of their norms:
$$|\langle u, v \rangle| \le \|u\|\|v\|$$

## Best Approximation Theorem

Many optimization applications can be converted to the following best approximation problem. We have a linear subspace $U \subseteq V$ and a vector $v \notin U$. We want to find the vector $v^* \in U$ that is closest to $v$ in the norm, that is, we want to solve
$$\min_{v^* \in U} \|v^* - v\|$$

**Definition 5** *(Orthogonal projection)*. Let $U \subseteq V$ be a linear subspace with orthonormal basis $q_1, \dots, q_m$. The orthogonal projection of $v \in V$ on $U$ is defined as
$$P_U v = \sum_{j=1}^{m} \langle v, q_j \rangle q_j$$

**Theorem 2** *(Best approximation theorem)*. Let $U \subseteq V$ be a linear subspace with orthonormal basis $q_1, \dots, q_m$ and let $v \in V$. For any $u \in U$,
$$\|v - P_U v\| \le \|v - u\|$$
Furthermore, if $u \in U$ and the inequality above is an equality, then $u = P_U v$.

**Lemma 4** *(Orthogonal decomposition)*. Let $U \subseteq V$ be a linear subspace with orthonormal basis $q_1, \dots, q_m$ and let $v \in V$. For any $u \in U$,
$$\langle v - P_U v, u \rangle = 0$$
In particular, $v$ can be decomposed as $(v - P_U v) + P_U v$ where the two terms are orthogonal.

We can test our best approximation by constructing a matrix $Q$ with columns $q_1, \dots, q_m$ and checking that:
$$Q^T Q = \begin{pmatrix}
\langle q_1, q_1 \rangle & \cdots & \langle q_1, q_m \rangle \\
\langle q_2, q_1 \rangle & \cdots & \langle q_2, q_m \rangle \\
\vdots & \ddots & \vdots \\
\langle q_m, q_1 \rangle & \cdots & \langle q_m, q_m \rangle
\end{pmatrix} = I_{m \times m}$$
where $I_{m \times m}$ denotes the $m \times m$ identity matrix.


In [5]:
# 1.2.2 Orthogonality
# Orthonormal Bases
def inner_product(u, v):
    return np.dot(u, v)
def norm(b):
    return np.sqrt(inner_product(b, b))
# Show if orthogoal/orthonormal vectors
def check_ortho(u, v):
    is_gonal = np.isclose(inner_product(u, v), 0.0)
    is_normal = is_gonal and np.isclose(norm(u), 1.0) and np.isclose(norm(v), 1.0)
    return print("Orthgonal?", is_gonal, "Orthonormal?", is_normal)
# Show Cauchy-Swartz THM
def cauchy_schwarz(u, v):
    lhs = abs(inner_product(u, v))
    rhs = norm(u) * norm(v)
    result = lhs <= rhs or np.isclose(lhs, rhs)
    print("Cauchy-Schwarz Satisfied?", result)
    return result
# Show Orthogonal Proj and Decomp
def o_decomp(u, v):
    proj_v_on_u = (inner_product(v, u)) / inner_product(u, u) * u
    prep_v_on_u = v - proj_v_on_u
    print("Orthogonal Decompostion's Projection of v on u", proj_v_on_u)
    # verify using best approx thm
    is_orthogonal_residual = np.isclose(inner_product(prep_v_on_u, u), 0.0)
    print(f"  Best Approximation Check (perp ⊥ u): {is_orthogonal_residual}")
    return proj_v_on_u, prep_v_on_u

# Now Example with u1 and u2
print("\nOrthogonality & Orthonormality Check")
check_ortho(u1, u2)
print("\nCauchy-Schwarz Theorem Verification")
cauchy_schwarz(u1, u2)
print("\nOrthogonal Decomposition & Best Approximation")
proj_vector, perp_vector = o_decomp(u1, u2)
print("Orthogonal Decomposition's Perpendicular component:", perp_vector)



Orthogonality & Orthonormality Check
Orthgonal? False Orthonormal? False

Cauchy-Schwarz Theorem Verification
Cauchy-Schwarz Satisfied? True

Orthogonal Decomposition & Best Approximation
Orthogonal Decompostion's Projection of v on u [7.33333333 7.33333333 7.33333333]
  Best Approximation Check (perp ⊥ u): True
Orthogonal Decomposition's Perpendicular component: [ 1.66666667 -1.33333333 -0.33333333]


**Theorem 3** *(Gram–Schmidt)*. Let $a_1, \dots, a_m$ in $\mathbb{R}^n$ be linearly independent. Then there exists an orthonormal basis $q_1, \dots, q_m$ of $\operatorname{span}(a_1, \dots, a_m)$.

## Gram–Schmidt Process

1. **Initialization ($k=0$):**
   - Code: `U[:, 0] = M[:, 0]` and `E[:, 0] = U[:, 0] / np.linalg.norm(U[:, 0])`
   - Takes the first vector $a_1$ and normalizes it to create the first orthonormal basis vector:
     $$q_1 = \frac{a_1}{\|a_1\|}$$
2. **Sequential Orthogonalization ($k = 1, \dots, m-1$):**
   - Code: `u_k = M[:, k].copy()` followed by the inner loop subtracting projections.
   - For each subsequent vector $a_k$ (the $k$-th column), we remove its components along all previously established orthogonal directions $u_1, \dots, u_{k-1}$ (or their normalized versions $q_j$). This isolates the part of $a_k$ that is strictly orthogonal to the subspace spanned by the previous vectors:
     $$u_k = a_k - \sum_{j=1}^{k-1} \langle a_k, q_j \rangle q_j$$
3. **Normalization:**
   - Code: `E[:, k] = U[:, k] / np.linalg.norm(U[:, k])`
   - Scales the newly orthogonalized vector $u_k$ to have a norm of 1, yielding the next orthonormal basis vector $q_k$:
     $$q_k = \frac{u_k}{\|u_k\|}$$
4. **Verification ($Q^T Q = I$):**
   - Code: `np.dot(gs_A.T, gs_A)`
   - Checks that all column vectors $q_i$ are mutually orthogonal ($\langle q_i, q_j \rangle = 0$ for $i \neq j$) and normalized ($\|q_i\|^2 = 1$), confirming that $Q^T Q = I_{m \times m}$ as established in the theory.

In [6]:
# 1.2.3 Gran-Schmidt Process
def gram_schmidt_matrix(Matrix_Input):
    M = Matrix_Input.astype('float64')
    rows, cols = M.shape
    # U holds the orthogonal vectors, E holds the normalized orthonormal vectors
    U = np.zeros((rows, cols))
    E = np.zeros((rows, cols))
    # Process first column
    U[:, 0] = M[:, 0]
    E[:, 0] = U[:, 0] / np.linalg.norm(U[:, 0])
    # Process remaining columns
    for k in range(1, cols):
        u_k = M[:, k].copy()
        # Subtract projections onto all previously established orthogonal vectors
        for j in range(k):
            u_k -= proj(U[:, j], M[:, k])
        U[:, k] = u_k
        E[:, k] = U[:, k] / np.linalg.norm(U[:, k])
    return E
# Calculate the Gram-Schmidt Matrix of A
gs_A = gram_schmidt_matrix(A)
print("Gram-Schmidt Orthonormal Matrix of A:\n", gs_A)
# Verify identity (Q^T * Q = I)
identity_check = np.dot(gs_A.T, gs_A)
print("\nVerification (Identity Matrix Check gs_A^T * gs_A):\n", np.round(identity_check, 6))

Gram-Schmidt Orthonormal Matrix of A:
 [[ 0.57735027  0.77151675 -0.26726124]
 [ 0.57735027 -0.6172134  -0.53452248]
 [ 0.57735027 -0.15430335  0.80178373]]

Verification (Identity Matrix Check gs_A^T * gs_A):
 [[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


## Eigenvalues and Eigenvectors

**Definition 6** *(Eigenvalues and eigenvectors)*. Let $A \in \mathbb{R}^{d \times d}$ be a square matrix. Then $\lambda \in \mathbb{R}$ is an eigenvalue of $A$ if there exists a non-zero vector $x \neq 0$ such that
$$Ax = \lambda x$$
The vector $x$ is referred to as an eigenvector.

**Lemma 5** *(Number of eigenvalues)*. Let $A \in \mathbb{R}^{d \times d}$ and let $\lambda_1, \dots, \lambda_m$ be distinct eigenvalues of $A$ with corresponding non-zero eigenvectors $x_1, \dots, x_m$. Then $x_1, \dots, x_m$ are linearly independent. As a result, $m \le d$.

**Theorem 4** *(Orthogonality of eigenvectors)*. If $A$ is symmetric, then any two eigenvectors from different eigenspaces are orthogonal.

**Theorem 5** *(The spectral theorem for symmetric matrices)*. An $n \times n$ symmetric matrix $A$ has the following properties:
* $A$ has $n$ real eigenvalues, counting multiplicities.
* If $\lambda$ is an eigenvalue of $A$ with multiplicity $k$, then the eigenspace for $\lambda$ is $k$-dimensional.
* The eigenspaces are mutually orthogonal, in the sense that eigenvectors corresponding to different eigenvalues are orthogonal.
* $A$ is orthogonally diagonalizable.

**Theorem 6** *(Rayleigh quotient optimization)*. Let $A$ be an $n \times n$ symmetric matrix with an orthogonal diagonalization $A = PDP^{-1}$ (where $P^{-1} = P^T$). The columns of $P$ are orthonormal eigenvectors $v_1, \dots, v_n$ of $A$. Assume that the diagonals of $D$ are arranged so that $\lambda_1 \le \lambda_2 \le \dots \le \lambda_n$. Then
$$\min_{x \neq 0} \frac{x^T A x}{x^T x} = \lambda_1$$
is achieved when $x = v_1$, and
$$\max_{x \neq 0} \frac{x^T A x}{x^T x} = \lambda_n$$
is achieved when $x = v_n$.


In [7]:
# 1.2.4 Eigenvalues and Eigenvectors
# Calculate Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A.astype(float))
print("Eigenvalues of Matrix A:\n", eigenvalues)
print("\nEigenvectors of Matrix A (as columns):\n", eigenvectors)

# Verification of A * v = lambda * v for the first eigenvalue/eigenvector pair
lambda_1 = eigenvalues[0]
v_1 = eigenvectors[:, 0]
left_side = np.dot(A, v_1)
right_side = lambda_1 * v_1
print("\nVerification of A * v = lambda * v for first pair:")
print("A * v_1:\n", left_side)
print("lambda_1 * v_1:\n", right_side)
print(f"Are both sides equal? {np.allclose(left_side, right_side)}")

Eigenvalues of Matrix A:
 [14.709785   -1.20385586  6.49407087]

Eigenvectors of Matrix A (as columns):
 [[ 0.37805486  0.82326091 -0.37597728]
 [ 0.40787016 -0.567488   -0.06241519]
 [ 0.83109353 -0.01410139  0.92452443]]

Verification of A * v = lambda * v for first pair:
A * v_1:
 [ 5.56110569  5.99968229 12.22520718]
lambda_1 * v_1:
 [ 5.56110569  5.99968229 12.22520718]
Are both sides equal? True
